"""LinguaForge — Hugging Face Space (static showcase).

This Space displays the **real held-out evaluation results** from our
`linguaforge-eval` Kaggle kernel: every output below was generated by the
actual base Gemma 4 E4B and the actual LinguaForge LoRA on FLORES-200 /
ChrEn devtest sentences they had never seen during training.

Live inference is intentionally not bundled here:

* Gemma 4 E4B + LoRA in 4-bit needs ~5 GB VRAM (won't fit on free CPU
  Spaces) and ZeroGPU requires HF Pro.
* Reproducing inference is one click on Kaggle: every kernel that
  produced the numbers below is public and re-runnable on a free T4 —
  links are right under the title.

License: code Apache-2.0, demo adapter CC-BY-SA 4.0.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import gradio as gr


HERE = Path(__file__).parent
EVAL_JSON = HERE / "eval_results.json"
LISTEN_JSON = HERE / "listen_results.json"


def _load_json(path: Path) -> dict:
    if path.exists():
        with path.open(encoding="utf-8") as f:
            return json.load(f)
    return {}


EVAL = _load_json(EVAL_JSON)
LISTEN = _load_json(LISTEN_JSON)


HEADER = textwrap.dedent(
    """
    # 🌍 LinguaForge — Gemma 4 E4B LoRA across 204 languages

    A 169.7 MB LoRA on top of
    [`google/gemma-4-E4B-it`](https://huggingface.co/google/gemma-4-E4B-it),
    trained on **all 203 non-English languages in FLORES-200** plus
    Cherokee from the **ChrEn** corpus — 33,480 chat samples, ~5 h on a free
    Kaggle T4.

    | What | Where |
    |---|---|
    | Adapter weights (HF) | <https://huggingface.co/zcgf111/linguaforge-gemma4-204lang-lora> |
    | Code (GitHub) | <https://github.com/dongwei05/LinguaForge> |
    | Training kernel | <https://www.kaggle.com/code/dongwei666/linguaforge-auto> |
    | Eval kernel (these numbers) | <https://www.kaggle.com/code/dongwei666/linguaforge-eval> |
    | Listen pillar (audio) | <https://www.kaggle.com/code/dongwei666/linguaforge-listen> |
    | GGUF Q4_K_M export | <https://www.kaggle.com/code/dongwei666/linguaforge-gguf> |

    > **Why static, not live?** Gemma 4 E4B + LoRA needs ~5 GB GPU RAM, and
    > HF ZeroGPU requires a paid HF Pro plan. Every output you see here
    > was produced by the **real** base Gemma 4 and the **real** LinguaForge
    > LoRA, on held-out FLORES-200 / ChrEn sentences they never saw during
    > training — re-runnable in one click on the eval kernel above.
    """
)


def _aggregate_table_md() -> str:
    if not EVAL:
        return "_eval_results.json not bundled — see the eval kernel link above._"
    rows = []
    for code, r in EVAL.get("results", {}).items():
        delta_chrf = r.get("d_chrf", 0)
        marker = "📈" if delta_chrf > 0.5 else ("📉" if delta_chrf < -0.5 else "≈")
        rows.append(
            f"| {r['label']} | `{code}` | {r['base_bleu']:.2f} | "
            f"**{r['lora_bleu']:.2f}** | {r['base_chrf']:.2f} | "
            f"**{r['lora_chrf']:.2f}** | {marker} {delta_chrf:+.2f} |"
        )
    agg = EVAL.get("aggregate", {})
    rows.append(
        f"| **mean (6 langs)** | — | {agg.get('base_bleu', 0):.2f} | "
        f"**{agg.get('lora_bleu', 0):.2f}** | {agg.get('base_chrf', 0):.2f} | "
        f"**{agg.get('lora_chrf', 0):.2f}** | {agg.get('d_chrf', 0):+.2f} |"
    )
    body = "\n".join(rows)
    return (
        "### Held-out FLORES-200 / ChrEn devtest — 50 sentences/language\n\n"
        "| Language | Code | base BLEU | +LoRA BLEU | base chrF | +LoRA chrF | Δ chrF |\n"
        "|---|---|---:|---:|---:|---:|---:|\n"
        f"{body}\n\n"
        "_Greedy decoding (`do_sample=False`), 128 max-new-tokens, on Kaggle T4._\n"
        "_Yoruba regression is reported transparently — see the writeup for the analysis._\n"
    )


def _sample_for_language(code: str, idx: int = 0) -> tuple[str, str, str, str]:
    samples = EVAL.get("samples", {}).get(code, [])
    if not samples:
        return "—", "—", "—", "—"
    if idx >= len(samples):
        idx = 0
    s = samples[idx]
    return s.get("en", ""), s.get("ref", ""), s.get("base", ""), s.get("lora", "")


LANG_CHOICES = []
for code, r in EVAL.get("results", {}).items():
    LANG_CHOICES.append((f"{r['label']} — {code}", code))


def show_sample(code: str, idx_label: str) -> tuple[str, str, str, str, str]:
    idx = {"first": 0, "second": 1, "third": 2}.get(idx_label, 0)
    en, ref, base, lora = _sample_for_language(code, idx)
    r = EVAL.get("results", {}).get(code, {})
    summary = (
        f"### {r.get('label', code)}\n\n"
        f"**Held-out scores** (50 sentences): "
        f"BLEU {r.get('base_bleu', 0):.2f} → **{r.get('lora_bleu', 0):.2f}** · "
        f"chrF {r.get('base_chrf', 0):.2f} → **{r.get('lora_chrf', 0):.2f}** "
        f"({r.get('d_chrf', 0):+.2f})"
    )
    return summary, en, ref, base, lora


LISTEN_INTRO = textwrap.dedent(
    """
    ### Cherokee Morning Song — Gemma 4 multimodal audio

    We loaded the real Wikimedia Commons recording of *Morning Song on
    Cherokee Hymns* (Bono.Ruma, CC-BY-SA 4.0) into Gemma 4 E4B's audio
    input head. Both runs (base and +LoRA) use the same multimodal chat
    template; outputs below are verbatim from the
    [`linguaforge-listen`](https://www.kaggle.com/code/dongwei666/linguaforge-listen)
    kernel.

    The point of this tab is to be honest about what works and what
    doesn't: the base model produces a graceful description; the LoRA
    enters a generation loop on this audio, which we discuss in the
    writeup as the next obvious thing to fix.
    """
)


def listen_block() -> str:
    if not LISTEN:
        return "_listen_results.json not bundled — see the Listen kernel link above._"
    src = LISTEN.get("audio_source", {})
    prompt = LISTEN.get("prompt", "")
    base = LISTEN.get("base_output", "")
    lora = LISTEN.get("lora_output", "")
    audio_md = (
        f"**Audio:** *{src.get('title', '?')}* — "
        f"{src.get('duration_sec', '?')} s — "
        f"by {src.get('author', '?')} ({src.get('license', '?')})\n\n"
        f"<{src.get('url', '')}>\n\n"
    )
    return (
        LISTEN_INTRO
        + "\n\n"
        + audio_md
        + f"**Prompt** (sent to both runs):\n\n```\n{prompt}\n```\n\n"
        + f"**Base Gemma 4 E4B output:**\n\n```\n{base}\n```\n\n"
        + f"**+ LinguaForge LoRA output:**\n\n```\n{lora}\n```\n"
    )


def build_demo() -> gr.Blocks:
    with gr.Blocks(
        title="LinguaForge — Gemma 4 multilingual LoRA",
        theme=gr.themes.Soft(primary_hue="amber"),
    ) as demo:
        gr.Markdown(HEADER)

        with gr.Tab("Numbers"):
            gr.Markdown(_aggregate_table_md())

        with gr.Tab("Side-by-side outputs"):
            gr.Markdown(
                "Pick a language and a sample to see **base Gemma 4** vs "
                "**+LinguaForge LoRA** on a held-out FLORES-200 / ChrEn sentence."
            )
            with gr.Row():
                lang_dd = gr.Dropdown(
                    choices=LANG_CHOICES if LANG_CHOICES else [("(none)", "")],
                    value=(LANG_CHOICES[0][1] if LANG_CHOICES else ""),
                    label="Language",
                )
                idx_radio = gr.Radio(
                    choices=["first", "second", "third"],
                    value="first",
                    label="Held-out sample",
                )
            summary_md = gr.Markdown()
            en_box = gr.Textbox(label="English source", lines=2)
            ref_box = gr.Textbox(label="Reference translation (FLORES-200/ChrEn)", lines=2)
            with gr.Row():
                base_box = gr.Textbox(label="Base Gemma 4 E4B (no adapter)", lines=4)
                lora_box = gr.Textbox(label="+ LinguaForge LoRA", lines=4)

            for ev in (lang_dd.change, idx_radio.change, demo.load):
                ev(
                    show_sample,
                    [lang_dd, idx_radio],
                    [summary_md, en_box, ref_box, base_box, lora_box],
                )

        with gr.Tab("Listen pillar (audio)"):
            gr.Markdown(listen_block())

        with gr.Tab("How to run live"):
            gr.Markdown(
                textwrap.dedent(
                    """
                    The full live demo (interactive translation + tutor chat) runs
                    in three places, all free to reproduce:

                    1. **Kaggle**: open
                       [`linguaforge-eval`](https://www.kaggle.com/code/dongwei666/linguaforge-eval)
                       and click **Copy & Edit** → **Run all** on a free T4 (~3 h).
                       It reproduces every number in the *Numbers* tab.
                    2. **Local Ollama** (CPU, 4 GB RAM):
                       ```bash
                       # download the GGUF Q4_K_M (5.0 GB) and Modelfile from the GGUF kernel
                       ollama create linguaforge -f Modelfile
                       ollama run linguaforge
                       ```
                    3. **Custom GPU Space**: clone
                       [`zcgf111/LinguaForge`](https://huggingface.co/spaces/zcgf111/LinguaForge),
                       upgrade hardware to ZeroGPU (HF Pro), and re-enable the
                       inference path in `app.py` — the LoRA loads via Unsloth
                       in <30 s.

                    Adapter is fully open: 169.7 MB at
                    <https://huggingface.co/zcgf111/linguaforge-gemma4-204lang-lora>.
                    """
                )
            )

        gr.Markdown(
            "---\n"
            "Adapter: 42.4M trainable params (0.53 % of 8B). Training: 8,370 steps, "
            "5 h 09 min on a Kaggle T4. Base model © Google DeepMind. "
            "FLORES-200 © Meta NLLB Team. ChrEn © Zhang, Frey, Bansal (EMNLP 2020). "
            "[Source code](https://github.com/dongwei05/LinguaForge) (MIT) · "
            "Adapter weights CC-BY-SA 4.0."
        )

    return demo


if __name__ == "__main__":
    build_demo().launch()
